/**
 * Repository Analysis Workflow
 * ----------------------------
 * This workflow orchestrates comprehensive repository analysis by combining
 * multiple tools to provide detailed insights about GitHub repositories.
 *
 * Components included:
 * - Repository Statistics Collection
 * - Contributor Analysis
 * - Activity Tracking
 * - Pull Request Metrics
 * - Repository Status Assessment
 */

import { createWorkflow, createStep } from "@mastra/core/workflows";
import { z } from "zod";
import { fetchRepositoryMetrics } from "./repository-metrics-tool";

// Create a step for comprehensive repository analysis
const performRepositoryAnalysis = createStep({
  id: "perform-repository-analysis",
  description:
    "Conduct comprehensive analysis of a GitHub repository and generate detailed report",
  inputSchema: z.object({
    repoUrl: z.string().describe("GitHub repository URL to analyze"),
  }),
  outputSchema: z.object({
    analysis: z.string(),
  }),
  execute: async ({ inputData }) => {
    if (!inputData) {
      throw new Error("Input data not found");
    }

    const result = await fetchRepositoryMetrics(inputData.repoUrl);

    // Format the result as a comprehensive markdown report
    const analysis = `# 🔍 Repository Analysis: ${result.repository.fullName}

## 📋 Repository Overview
- **Repository Name**: ${result.repository.name}
- **Full Repository Name**: ${result.repository.fullName}
- **Repository Owner**: ${result.repository.owner} (${result.repository.ownerType})
- **Repository Description**: ${result.repository.description || "No description available"}

## 📊 Key Metrics
- ⭐ **Total Stars**: ${result.statistics.stars.toLocaleString()}
- 🍴 **Total Forks**: ${result.statistics.forks.toLocaleString()}
- 🐛 **Open Issues**: ${result.statistics.openIssues.toLocaleString()}
- 👀 **Watchers**: ${result.statistics.watchers.toLocaleString()}
- 💻 **Primary Language**: ${result.statistics.primaryLanguage || "Not specified"}

## 👥 Top Contributors
${result.contributors
  .map(
    (contributor: any) =>
      `- **${contributor.username}**: ${contributor.contributions} contributions`
  )
  .join("\n")}

## 📅 Activity Timeline
- **Last Push**: ${new Date(result.activity.lastPush).toLocaleDateString()}
- **Last Update**: ${new Date(result.activity.lastUpdate).toLocaleDateString()}
- **Repository Created**: ${new Date(result.activity.createdAt).toLocaleDateString()}

## 🔄 Pull Request Statistics
- **Open Pull Requests**: ${result.pullRequests.open}
- **Closed Pull Requests**: ${result.pullRequests.closed}
- **Total Pull Requests**: ${result.pullRequests.total}

## 📄 License Information
${result.license ? `- **${result.license.name}** (${result.license.spdxId})` : "- No license specified"}

## 🔒 Repository Status
- **Private Repository**: ${result.status.isPrivate ? "Yes" : "No"}
- **Archived Repository**: ${result.status.isArchived ? "Yes" : "No"}
- **Disabled Repository**: ${result.status.isDisabled ? "Yes" : "No"}

---

*Analysis generated by Repository Intelligence Agent* 🌟`;

    return { analysis };
  },
});

export const repoAnalyzerWorkflow = createWorkflow({
  id: "repo-analyzer-workflow",
  inputSchema: z.object({
    repoUrl: z.string().describe("GitHub repository URL to analyze"),
  }),
  outputSchema: z.object({
    analysis: z.string(),
  }),
}).then(performRepositoryAnalysis);

repoAnalyzerWorkflow.commit();
